"""Beginner-friendly starter investment guides. Tax and return text needs periodic review."""

from .models import InvestmentGuide

_GUIDES = [
    ("savings-account", "Savings account", "India", "Cash", "Low", "A bank account for money you may need soon.", "Deposit money, then withdraw or pay when needed; the bank may add interest.", "₹10,000 may earn a small amount of interest while staying easy to access.", "Interest paid by the bank.", "Around 2–4% a year; varies by bank and time.", "Immediate needs", "Often ₹0; bank rules vary.", "Usually instant by transfer or ATM, subject to limits.", "Interest is generally taxable; exemptions and reporting depend on your situation.", "People building a cash buffer.", "Money meant for decades of growth alone.", "Ignoring fees, limits, or deposit protection terms.", "Easy access; simple to understand.", "Returns may not keep up with inflation.", "It is a safe pocket for money you might need quickly."),
    ("fixed-deposit", "Fixed deposit", "India", "Cash and deposits", "Low", "A bank or post-office deposit kept for a chosen time at a stated rate.", "Choose an amount and term; the institution pays interest under its terms.", "A ₹50,000 deposit for one year earns interest at the offered rate, before tax.", "Interest; early withdrawal may reduce it.", "Often about 5–8% historically; rates change and are taxable.", "Short to medium", "Often ₹1,000 or provider minimum.", "Usually available early with a possible penalty.", "Interest is generally taxed at your income-tax slab; withholding may apply.", "People who value predictable interest and can choose a term.", "People who may need all the money at any moment.", "Renewing without checking rates, tax, and early-exit rules.", "Known term and rate; relatively simple.", "Inflation and tax can reduce the real return.", "You lend the bank your money for a set time and get interest."),
    ("recurring-deposit", "Recurring deposit", "India", "Cash and deposits", "Low", "A deposit where you save a fixed amount regularly for a chosen term.", "Set a monthly deposit; interest is added according to provider terms.", "Save ₹1,000 each month for a year and receive the deposits plus interest.", "Interest on regular deposits.", "Often around 5–8% historically; varies and is not a promise.", "Short to medium", "Commonly ₹100–₹500 monthly; varies.", "Early closure may reduce interest or incur a charge.", "Interest is generally taxable at your income-tax slab.", "People who want a savings habit and a set date.", "People with irregular income or no cash buffer.", "Missing instalments and overlooking tax.", "Encourages steady saving.", "Less flexible than a savings account.", "It is like a fixed deposit built one monthly payment at a time."),
    ("ppf", "Public Provident Fund (PPF)", "India", "Government savings", "Low", "A long-term government-backed savings account with a lock-in and changing notified rate.", "Make deposits within annual rules; interest is set by the government and compounded.", "Putting in ₹500 a month builds a long-term balance, but money is not freely withdrawable.", "Notified interest; maturity proceeds follow current tax rules.", "Rates are set periodically; past rates are not future rates.", "Long term", "₹500 yearly minimum under current scheme rules; verify before investing.", "Long lock-in with limited loan and withdrawal windows.", "Often described as tax-favoured; verify current eligibility and regime rules.", "People saving for distant goals who accept lock-in.", "People who need quick access or have high-cost debt.", "Missing minimum deposits or assuming all withdrawals are free.", "Government-backed scheme; supports a long horizon.", "Long lock-in and annual contribution limits.", "You save for many years in a government scheme with restricted access."),
    ("epf", "Employees’ Provident Fund (EPF)", "India", "Retirement", "Low", "A retirement savings scheme for eligible employees and employers.", "Employee and employer contributions go into the account; interest is credited under scheme rules.", "A salary contribution and employer contribution accumulate across working years.", "Scheme interest and eligible withdrawals.", "Rate is notified each year and can change; not guaranteed forever.", "Long term", "Payroll contribution as per eligibility and salary rules.", "Withdrawals are restricted and subject to scheme rules.", "Tax depends on contributions, service, withdrawals, and current rules.", "Eligible employees building retirement savings.", "People needing their full balance for routine spending.", "Withdrawing early without considering tax and retirement impact.", "Automatic payroll saving; employer contribution may apply.", "Access is restricted and rules are detailed.", "Part of your pay is saved for retirement under a formal scheme."),
    ("nps", "National Pension System (NPS)", "India", "Retirement", "Medium", "A regulated retirement account invested across selected asset classes.", "Choose a scheme and allocation; contributions are invested and account value moves with markets.", "A ₹1,000 contribution buys units; their value can rise or fall over time.", "Market-linked gains and retirement withdrawals under rules.", "Market-linked; no fixed return or guarantee.", "Long term", "Typically low minimums; account and contribution rules apply.", "Limited before retirement; exit rules apply.", "Tax benefits and withdrawal taxation depend on current law and account type.", "People saving for retirement who accept market movement and rules.", "People needing unrestricted near-term access.", "Choosing an allocation without understanding exit rules.", "Diversified choices; retirement focus.", "Rules constrain access and withdrawal choices.", "It is a long-term retirement pot invested in a mix of assets."),
    ("sukanya-samriddhi", "Sukanya Samriddhi Account", "India", "Government savings", "Low", "A government small-savings scheme for an eligible girl child.", "An eligible guardian opens an account and makes deposits under scheme rules.", "A family saves regularly toward future education or other eligible needs.", "Notified interest, subject to scheme rules.", "Rate is periodically notified; past rates do not promise future rates.", "Long term", "Minimum deposit is set by scheme rules; verify current amount.", "Withdrawals are limited and tied to purpose and age rules.", "Tax treatment is subject to current scheme and tax rules.", "Eligible families with a long-term goal for a girl child.", "Anyone needing general-purpose liquid savings.", "Missing deposits or assuming unrestricted withdrawals.", "Purpose-built and government-backed.", "Eligibility and access are restricted.", "A special long-term savings account for an eligible girl child."),
    ("mutual-fund-index", "Index mutual fund", "India", "Mutual funds", "High", "A fund that aims to follow a market index by holding similar investments.", "Invest a lump sum or set a SIP; the fund buys a basket and NAV changes with markets.", "₹500 can buy units in a Nifty index fund; value follows the fund’s holdings and costs.", "The fund value may rise through market growth and distributions.", "Market-linked; no guaranteed range. Compare index and period before using history.", "Medium to long", "Often ₹100–₹500 SIP, depending on fund.", "Usually redeemable on business days; settlement and exit rules vary.", "Tax depends on fund classification, holding period, and current law.", "People seeking broad market exposure at relatively low cost.", "People who cannot tolerate market falls or need the money soon.", "Chasing recent returns and ignoring tracking difference or costs.", "Broad exposure; simple approach.", "Can fall sharply; tracks its index down too.", "One fund can give you tiny pieces of many companies in an index."),
    ("sip", "Systematic Investment Plan (SIP)", "India", "Mutual funds", "Varies", "A way to invest a chosen amount into a mutual fund regularly.", "Choose a fund and schedule; each payment buys units at that day’s NAV.", "A ₹1,000 monthly SIP buys more units when the NAV is lower and fewer when higher.", "Returns come from the selected fund, not from the SIP method itself.", "Depends entirely on the fund; no guaranteed return.", "Depends on goal and fund", "Fund SIP minimum, often ₹100–₹500.", "Depends on the fund’s redemption and exit rules.", "Tax follows the chosen fund and current rules.", "People who prefer a regular investing routine.", "Anyone expecting SIPs to remove market risk or guarantee profit.", "Stopping in a downturn without revisiting the goal and risk.", "Builds a habit; spreads purchase dates.", "Does not protect against losses or poor fund choice.", "SIP is a payment schedule, like a monthly subscription into an investment."),
    ("direct-stocks", "Direct shares", "India", "Stocks", "Very High", "A share represents a small ownership stake in a listed company.", "Open a regulated brokerage account, research a company, and place an order.", "₹2,000 buys shares according to market price and charges; the price may rise or fall.", "Possible share-price gains and dividends; neither is certain.", "Highly variable; individual shares can lose most or all value.", "Long term", "Share price plus brokerage and other charges.", "Listed shares can usually be sold during market hours, at the available price.", "Tax depends on holding period, transaction type, and current law.", "People willing to research businesses and accept loss risk.", "People needing stable returns or acting on tips.", "Concentrating in one name or trading borrowed money.", "Direct ownership; transparent market price.", "Company-specific risk; prices can move sharply.", "You own a tiny slice of one company, so its success matters a lot."),
    ("government-bonds", "Government bonds and Treasury bills", "India", "Bonds", "Low to Medium", "A loan to the government for a stated term, with interest or discounted repayment terms.", "Buy at issue or in a market; hold to maturity or sell if a market is available.", "A ₹10,000 bond may pay scheduled interest; market price can change before maturity.", "Coupon interest and possible price change.", "Yield depends on issue and purchase price; not a promise for market value.", "Short to long", "Varies by issue and platform.", "Market sale may take time and price can be above or below purchase price.", "Interest and gains have tax rules that depend on instrument and current law.", "People seeking government debt exposure and understanding maturity.", "People who need guaranteed access at the original price.", "Selling before maturity without checking interest-rate risk.", "Issuer credit risk is generally considered lower than corporate debt.", "Market prices can fall when rates rise.", "You lend to the government; selling early can change what you get back."),
    ("gold-etf", "Gold ETF", "India", "Gold", "Medium", "A market-traded fund designed to reflect gold prices, less costs and tracking differences.", "Buy fund units in a brokerage account; each unit represents a small gold exposure.", "₹1,000 buys units whose value moves with gold prices and currency effects.", "A rise in gold price may raise unit value; no interest is paid.", "Gold prices fluctuate; past performance is not a forecast.", "Medium to long", "One unit price plus brokerage; varies by ETF.", "Usually sold during market hours; settlement rules apply.", "Tax depends on purchase date, holding period, and current rules.", "People wanting exchange-traded gold exposure without storing bars.", "People expecting interest income or stable value.", "Ignoring tracking error, costs, and liquidity.", "No home storage; convenient market access.", "Price can be volatile and generates no cash yield.", "It lets you buy a small market-traded claim linked to gold."),
    ("reit", "REITs and InvITs", "India", "Listed funds", "Medium to High", "Listed trusts that own income-producing property or infrastructure assets.", "Buy listed units; trust income and unit prices depend on assets and markets.", "₹5,000 buys units in a property trust; rent distributions and price may vary.", "Possible distributions and price movement.", "Returns vary; distributions and prices are not guaranteed.", "Medium to long", "Market price of one unit plus charges.", "Sell on exchange when buyers are available; price may move.", "Tax treatment varies by distribution component and current law.", "People wanting listed exposure to property or infrastructure.", "People needing a guaranteed income or principal.", "Treating distributions as fixed and ignoring concentration.", "Tradable exposure without buying a building.", "Interest rates, tenants, projects, and market demand matter.", "You own units in a trust that holds buildings or infrastructure."),
    ("corporate-bonds", "Corporate bonds", "India", "Bonds", "Medium to High", "A loan to a company that may pay interest and return principal under its terms.", "Check issuer, credit rating, maturity, and price; buy and monitor the bond.", "A ₹10,000 bond may pay coupon interest, but a company can delay or default.", "Interest and possible price change.", "Yield varies with issuer risk and price; default losses are possible.", "Short to long", "Issue and platform minimums vary.", "Some bonds trade rarely; selling early may be difficult.", "Interest and gains are taxed under current instrument-specific rules.", "People able to assess issuer and liquidity risk.", "People who assume a rating means no risk.", "Chasing high yields without checking issuer finances.", "Scheduled coupon can be useful.", "Default and low liquidity can cause losses.", "You lend money to a company, which may fail to repay as promised."),
    ("us-etf", "US-listed ETF", "Outside India", "Global investments", "High", "A US-traded fund holding a basket of securities, often tracking an index.", "Use a permitted route, fund the account, and buy units; returns also reflect currency changes.", "A $50 purchase converts from rupees and gains or loses with both ETF price and USD/INR.", "Market gains or fund distributions, subject to costs and tax.", "Market and currency risk; no guaranteed range.", "Long term", "One share or fractional-share minimum, platform dependent.", "Exchange trading hours and settlement apply; cross-border withdrawal takes longer.", "Indian tax, foreign reporting, and withholding can apply; verify current rules.", "Investors who understand currency, tax, and cross-border costs.", "People needing rupee-stable short-term savings.", "Ignoring FX spreads, fees, reporting, or concentration.", "Access to markets outside India.", "Currency, foreign law, and market timing risks.", "The investment can move with both the foreign market and the rupee."),
    ("international-fund", "International mutual fund", "Outside India", "Global investments", "High", "A fund available to Indian investors that invests in foreign markets or funds.", "Invest rupees through the fund; the manager converts or invests abroad under its mandate.", "A ₹1,000 purchase gains or loses with foreign holdings and exchange rates.", "Foreign asset price movements and any distributions.", "Market-linked; no guaranteed return.", "Long term", "Fund minimum, often ₹100–₹5,000.", "Redemption depends on fund terms; some funds may restrict subscriptions.", "Tax depends on structure, holding date, and current law.", "People diversifying across countries who understand currency risk.", "People who need a known short-term value.", "Assuming global automatically means diversified.", "Convenient access through a domestic fund.", "Currency exposure and fund limits or costs.", "One rupee investment can give exposure to companies in other countries."),
    ("crypto", "Crypto assets", "Outside India", "Digital assets", "Very High", "Digital tokens traded on networks, with prices driven by uncertain demand and supply.", "Use a platform or wallet; transactions may be irreversible and custody matters.", "A ₹1,000 token purchase can quickly become worth much less or more.", "Only if someone else will buy later at a higher price or a token has utility; neither is certain.", "Extreme volatility; total loss, fraud, and custody failure are possible.", "Only money one can afford to lose; no reliable horizon.", "Platform minimum varies.", "Varies by token, platform, network congestion, and local rules.", "Indian tax and reporting rules can be strict and may change; seek qualified advice.", "Only informed users who understand custody and can bear total loss.", "Anyone using borrowed money or emergency savings.", "Fake exchanges, seed phrase theft, guaranteed-return schemes, and hype.", "Open networks can enable new applications.", "No dependable valuation anchor; severe operational and legal risk.", "It is a risky digital token; its price can collapse and recovery is not assured.", "High risk: not a savings product; beware scams and never share recovery phrases."),
    ("p2p-lending", "Peer-to-peer lending", "India", "Alternative", "Very High", "A platform connects lenders with borrowers who repay under loan terms.", "Choose loans through a regulated platform; borrower repayments may be late or never arrive.", "A ₹5,000 loan split across borrowers can still suffer defaults and collection delays.", "Borrower interest after fees and defaults.", "Advertised rates are not realized returns; loss of principal is possible.", "Medium to long", "Platform minimum varies.", "Often limited until borrowers repay; there may be no easy resale.", "Interest and losses have tax treatment under current rules.", "Experienced investors who accept borrower and platform risk.", "People requiring deposit-like safety or instant access.", "Believing diversification removes default risk.", "Can spread exposure among loans.", "Defaults and recovery delays can reduce principal.", "You lend to people through a platform; some may not pay you back.", "High risk: check current regulator rules, platform status, and recovery terms."),
    ("crypto-global-rules", "LRS and overseas investing basics", "Outside India", "Rules and taxes", "Medium", "A plain-language starting point for Indian residents sending money abroad to invest.", "Use an authorized bank or provider and follow current RBI, tax, FEMA, reporting, and platform rules.", "Before a ₹10,000 transfer, check fees, exchange rate, purpose rules, tax collection, and reporting.", "This is a compliance guide, not an investment or return source.", "Not applicable.", "Depends on investment", "Depends on provider and transfer rules.", "Cross-border transfer and repatriation can take time and require documents.", "LRS limits, TCS, tax, and reporting rules can change; verify official current guidance.", "Residents researching a lawful overseas investment route.", "Anyone relying on old social-media summaries.", "Ignoring exchange fees, TCS cash flow, disclosures, or FEMA conditions.", "Prompts careful planning and record keeping.", "Rules change and personal tax details matter.", "Before investing abroad, check the current rules with an authorized provider and tax professional.", "Rules change; this guide is educational and must be checked against official current guidance."),
]


def guide_records() -> list[InvestmentGuide]:
    """Create model objects with shared practical notes for all starter entries."""
    rows = []
    for row in _GUIDES:
        (slug, name, region, category, risk, what, how, example, earns, historical,
         horizon, minimum, liquidity, tax, suitable, avoid, mistakes, pros, cons, explain, *warning) = row
        rows.append(InvestmentGuide(
            slug=slug, name=name, region=region, category=category, risk_level=risk,
            what_is_it=what, how_it_works=how, example=example, how_you_may_earn=earns,
            historical_return_range=historical, time_horizon=horizon, minimum_amount=minimum,
            liquidity=liquidity, tax_note=tax, suitable_for=suitable, avoid_if=avoid,
            common_mistakes=mistakes, pros=pros, cons=cons, explain_like_15=explain,
            warning=warning[0] if warning else None,
        ))
    return rows
